### ISSUE TITLE
urdf

### ISSUE THREAD

**Issue by soldierofhell** [KNR-PW/MelsonKNR#5]
Witam, czy jest gdzieś dostępny urdf Melsona?

**Comment by pktiuk** [comment]
@KNR-PW/melman

**Comment by Domiziol** [comment]
[Melman.zip](https://github.com/KNR-PW/MelsonKNR/files/11524866/Melman.zip)

Wrzucam narazie urdf Melmana (sry ze .zip ale .urdf nie chciało przyjąć)

**Comment by Domiziol** [comment]
[Melson.zip](https://github.com/KNR-PW/MelsonKNR/files/11524881/Melson.zip)
Jednak Melsona też znalazłam :)

**Comment by pktiuk** [comment]
Może warto by to było też wrzucić gdzieś na repo?
Ewentualnie można stworzyć oddzielne repo z paczką rosową będącą symulatorem melmana tak jak zrobiło to selfie https://github.com/KNR-PW/gazebo_selfie_sim

**Comment by soldierofhell** [comment]
Dzięki!

**Comment by soldierofhell** [comment]
@Domiziol , czy mógłbym prosić też o dorzucenie STL-i wymaganych przez urdfa?

**Comment by Domiziol** [comment]
[STLeMelman.zip](https://github.com/KNR-PW/MelsonKNR/files/11531028/STLeMelman.zip)
[STLeMelson.zip](https://github.com/KNR-PW/MelsonKNR/files/11531111/STLeMelson.zip)
Tutaj STLe do obu robotów

[Melson_ROS-master.zip](https://github.com/KNR-PW/MelsonKNR/files/11531112/Melson_ROS-master.zip)
To jest repo z symulacją i sterowaniem do Melsona z dawnych czasów, może się komuś przyda

**Comment by pktiuk** [comment]
> [Melson_ROS-master.zip](https://github.com/KNR-PW/MelsonKNR/files/11531112/Melson_ROS-master.zip) To jest repo z symulacją i sterowaniem do Melsona z dawnych czasów, może się komuś przyda

Może przydałoby się je wrzucić gdzieś tutaj na githuba, np jako oddzielny branch/tag, aby było to dotępne w wygodnej formie.
